version: 2.1

aliases:
  # Define paths and never think about them again
  - &WORKSPACE /tmp/lunie
  - &docker-browsers tendermintdev/voyager_node_browser

# reusable commands
commands:
  yarn-install:
    description: '[YARN] update and install'
    steps:
      - restore_cache:
          keys:
            - v4-dependencies-root-{{ checksum "package.json" }}
            - v4-dependencies-root-

      - run: yarn install
      - save_cache:
          paths:
            - yarn.lock
            - node_modules
          key: v4-dependencies-root-{{ checksum "package.json" }}

jobs:
  pendingUpdated:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: yarn add simsala
      - run: node node_modules/simsala/src/cli.js check 

  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - yarn-install
      - run: yarn run lint

  testUnit:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - yarn-install
      # - run:
      #     name: Setup Code Climate test-reporter
      #     command: |
      #       # download test reporter as a static binary
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter
      - run:
          name: Test
          command: |
            # notify Code Climate of a pending test report using `before-build`
            # ./cc-test-reporter before-build
            yarn run initiate-submodule
            yarn run test
            # upload test report to Code Climate
            # ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
            # ./cc-test-reporter upload-coverage
          no_output_timeout: 120

  security:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Audit
          command: |
            set +e

            SUMMARY="$(yarn audit | grep Severity)"
            VULNERABILITIES=".*(High|Critical).*"

            if [[ $SUMMARY =~ $VULNERABILITIES ]]; then
              echo "Unsafe dependencies found: $SUMMARY" >&2
              exit 1
            fi
            echo "Your dependencies are secure enough: $SUMMARY"
            exit 0
  
  testE2E:
    docker:
      # Primary container image where all steps run.
     - image: *docker-browsers
      # Secondary container image on common network which runs the testnet
     - image: lunieio/testnet:v0.34.3
    steps:
      - checkout
      - attach_workspace:
          at: *WORKSPACE
      - yarn-install
      - setup_remote_docker
      - run:
          name: Build
          command: |
            npm run initiate-submodule
            npm run test:e2e:build
      - run:
          name: Test
          command: npm run test:e2e:start-lunie & yarn test:e2e
          no_output_timeout: 120
      - store_artifacts:
          path: ./screenshots
          when: on_fail

  # Create release.
  release:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: |
          yarn add simsala
          git config user.email "bot@lunie.io"
          git config user.name "Lunie Bot"
          node node_modules/simsala/src/cli.js release-candidate --semver prerelease --owner luniehq --repository lunie-browser-extension --token $GIT_BOT_TOKEN

  # Push merges to master immediatly back to develop to stay in sync
  mergeBack:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          command: |
            git remote add bot https://${GIT_BOT_TOKEN}@github.com/luniehq/lunie.git
            git checkout develop -f
            git pull -f --no-edit
            git merge origin/master --no-edit
            git push

  # publish to the Chrome Web Store
  publish:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - yarn-install
      - run: |
          npm run initiate-submodule
          npm run build
          npm run build-zip
          ./scripts/publish.sh ./dist-zip/lunie-browser-extension.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Static checks before
      - pendingUpdated:
          filters:
            branches:
              ignore:
                - release
                - master

      - security:
          filters:
            branches:
              ignore: release

      - lint:
          filters:
            branches:
              ignore: release

      - testUnit:
          filters:
            branches:
              ignore: release

      - testE2E:
          filters:
            branches:
              ignore: release

  releaseManually:
    jobs:
      - release:
          filters:
            branches:
              only:
                - release
  mergeBack:
    jobs:
      - mergeBack:
          filters:
            branches:
              only: master
  publish:
    jobs:
      - publish:
          filters:
            branches:	
              only: master
